# Generated by Django 6.0.2 on 2026-02-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_interviewer_app",
            "0002_appuser_full_name_userprofile_interviewquestion_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Scorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technical_score", models.FloatField()),
                ("communication_score", models.FloatField()),
                ("overall_score", models.FloatField()),
                ("skill_breakdown", models.JSONField(default=dict)),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecard",
                        to="ai_interviewer_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
